### ISSUE TITLE
get_ethtool_link_settings accesses a stale pointer

### ISSUE THREAD

**Issue by riking** [ssfdust/ethernet-info-rs#1]
https://asan.saethlin.dev/ub?crate=ethernet-info&version=0.0.2

```
    /// Convert the ifreq struct which is filled by kernel to the EthtoolCommnad.
    pub fn get_ethtool_link_settings(&self) -> EthtoolCommnad {
        unsafe {
            let ecmd = self.ifr.ifr_ifru.ifru_data as *mut EthtoolCommnad;
            *ecmd
        }
    }
```

This code is incorrect: you need to read the ifru_data out in the same function that performs the syscall, or otherwise preserve without moving (pin) the buffer you ask the syscall to write into.

```
test src/lib.rs - (line 7) ... FAILED

failures:

---- src/lib.rs - (line 7) stdout ----
Test executable failed (exit status: 1).

stderr:
=================================================================
==6647==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f6c1ff09ec0 at pc 0x5639ba1a753a bp 0x7fffc8d55160 sp 0x7fffc8d54920
READ of size 1572 at 0x7f6c1ff09ec0 thread T0
    #0 0x5639ba1a7539 in __asan_memcpy /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:63:3
    #1 0x5639ba1f0b48 in ethernet_info::internal::CmdContext::get_ethtool_link_settings::h5d28b23d78d7a185 /build/src/internal.rs:183:13
    #2 0x5639ba1e6fd3 in ethernet_info::do_ioctl_get_ethernet_info::h24f50557f2ea09a9 /build/src/lib.rs:124:12
    #3 0x5639ba1e60ea in _$LT$ethernet_info..EthernetInfo$u20$as$u20$core..convert..TryFrom$LT$$RF$str$GT$$GT$::try_from::h7144dc4821fca450 /build/src/lib.rs:107:29
    #4 0x5639ba1e867d in ethernet_info::get_ethernet_info::h3f44c496e548a0da /build/src/lib.rs:164:17
    #5 0x5639ba1d6286 in rust_out::main::_doctest_main_src_lib_rs_7_0::h9c21e53652e780ea /build/src/lib.rs:6:27
    #6 0x5639ba1d5ed5 in rust_out::main::h3c365c6a42822ba3 /build/src/lib.rs:12:3
```
```
Address 0x7f6c1ff09ec0 is located in stack of thread T0 at offset 7872 in frame
    #0 0x5639ba1e656f in ethernet_info::do_ioctl_get_ethernet_info::h24f50557f2ea09a9 /build/src/lib.rs:115

  This frame has 24 object(s):
    [32, 48) '' (line 115)
    [64, 1636) '_43' (line 148)
    [1776, 1880) '_42' (line 148)
    [1920, 1944) '_38' (line 141)
    [1984, 3556) '_32' (line 137)
    [3696, 3768) 'val4'
    [3808, 3832) 'residual3'
    [3872, 5444) '_28' (line 136)
    [5584, 5656) '_27' (line 136)
    [5696, 5768) '_26' (line 136)
    [5808, 5880) '_25' (line 136)
    [5920, 5944) '_21' (line 126)
    [5984, 7556) '_15' (line 124)
    [7696, 7768) 'val2'
    [7808, 7832) 'residual1'
    [7872, 9444) '_11' (line 123) <== Memory access at offset 7872 is inside this variable
    [9584, 9656) '_10' (line 123)
    [9696, 9768) '_9' (line 123)
    [9808, 9880) '_8' (line 123)
    [9920, 11492) 'val' (line 116)
    [11632, 11656) 'residual'
    [11696, 13272) '_4' (line 116)
    [13408, 14984) '_3' (line 116)
    [15120, 16692) 'ecmd' (line 116)
```
```
SUMMARY: AddressSanitizer: stack-use-after-scope /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:63:3 in __asan_memcpy
Shadow bytes around the buggy address:
  0x7f6c1ff09c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f6c1ff09c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f6c1ff09d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f6c1ff09d80: 04 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2
  0x7f6c1ff09e00: f2 f2 00 00 00 00 00 00 00 00 00 f2 f2 f2 f2 f2
=>0x7f6c1ff09e80: 00 00 00 f2 f2 f2 f2 f2[f8]f8 f8 f8 f8 f8 f8 f8
  0x7f6c1ff09f00: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x7f6c1ff09f80: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x7f6c1ff0a000: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x7f6c1ff0a080: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x7f6c1ff0a100: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6647==ABORTING
```

**Comment by ssfdust** [comment]
Thanks for reporting
